coverage:
  jacoco:
    projectDirectory: SystemTest
    #projectDirectory: /home/tegel/Courses/Thesis/Bears/repositories/webfirmframework-wff-453188520-453188718/wffweb
    parallel: true

mutation:
  pitest:
    projectDirectory: SystemTest

writer:
#  csv:
#    outputFile: MetricCollector/target/output.csv
  console: {}
