reader:
  jacoco:
#    targetDirectory: SystemTest/target/
#    targetDirectory: /home/tegel/Courses/Thesis/Bears/repositories/webfirmframework-wff-453188520-453188718
    targetDirectory: /home/tegel/Courses/Thesis/Bears/repositories/AxonFramework-AxonFramework-451926440-451937647
    parallel: true

writer:
#  csv:
#    outputFile: MetricCollector/target/output.csv
  console: {}
